dataset:
  d_type: train
  sequence_length: 2500
  custom_path: ./examples/train.mat
  ae_mode: True
dataloader:
  batch_size: 512
  shuffle: True
model_name: ConvAE
model_path: None
model:
  sequence_length: 2500
  features: 2
  extracted_features: 32
  latent_size: 128
  kernel_size: 500
  stride: 5
  padding: 0
  last_activation: sigmoid
precision: float32
train_epochs: 100
device: cuda