dataset:
  d_type: train
  sequence_length: 2500
  custom_path: ./examples/train.mat
  ae_mode: True
dataloader:
  batch_size: 64
  shuffle: True
model_name: ConvVAE
model_path: None
model:
  sequence_length: 2500
  features: 2
  extracted_features: 4
  latent_size: 16
  kernel_size: 25
  stride: 10
  padding: 0
  last_activation: sigmoid
precision: float32
train_epochs: 1
device: mps