dataset:
  d_type: train
  sequence_length: 4096
  custom_path: ./examples/train.mat
  ae_mode: True
dataloader:
  batch_size: 256
  shuffle: True
model_name: ConvAE
model_path: None
model:
  sequence_length: 4096
  features: 2
  extracted_features: 8
  latent_size: 32
  kernel_size: 129
  stride: 16
  last_activation: sigmoid
precision: float32
train_epochs: 5
device: cuda