dataset:
  d_type: train
  sequence_length: 1024
  custom_path: ./examples/train.mat
  ae_mode: True
dataloader:
  batch_size: 512
  shuffle: True
model_name: ConvAE
model_path: None
model:
  sequence_length: 1024
  features: 2
  extracted_features: 4
  latent_size: 16
  kernel_size: 31
  stride: 5
  last_activation: sigmoid
precision: float32
train_epochs: 10
device: mps