name: timeseries-dl
channels:
    - pytorch
    - conda-forge 
dependencies:
    - python=3.10
    - scikit-learn
    - numpy
    - scipy
    - pandas
    - matplotlib
    - tqdm
    - pyyaml
    - ipython
    - pytorch
    - lightning
    - torchvision
    - tensorboard
    - setuptools