name: timeseries-dl
channels:
    - pytorch
    - conda-forge 
dependencies:
    - python
    - scikit-learn
    - numpy<2.0
    - scipy
    - pandas
    - matplotlib
    - tqdm
    - pyyaml
    - ipython
    - pytorch
    - lightning
    - torchvision
    - tensorboard
    - mlflow
    - setuptools