name: timeseries-dl
channels:
    - pytorch
    - conda-forge 
    - nvidia
dependencies:
    - python
    - pytorch-cuda=12.1
    - scikit-learn
    - numpy<2.0
    - scipy
    - pandas
    - matplotlib
    - tqdm
    - pyyaml
    - ipython
    - pytorch=2.3.0
    - lightning
    - torchvision
    - mlflow
    - tensorboard
    - setuptools