device: cpu
model_name: ModelCNN-LSTM
model_args:
  log: True
  lr: 0.02
  lr_decay: 0.9
  adam_betas: [0.3, 0.5]
  kernel_size: 21
  channels: 5
  stride: 5
  padding: 10
  hidden_dim: 128
  xavier_init: True
  out_act: sigmoid
dataset_args:
  d_type: train
  normalize: True
  bounds: [0, 1]
  sequence_length: 200
dataloader_args:
  num_workers: 1
  batch_size: 100
  shuffle: True
train_epochs: 30
evaluation: None