device: cpu
model_name: ModelLSTMv2
model_args:
  log: True
  lr: 0.005
  lr_decay: 0.99
  adam_betas: [0.9, 0.999]
  hidden_dim: 128
  xavier_init: False
  out_act: linear
dataset_args:
  d_type: train
  normalize: True
  bounds: [0, 1]
  sequence_length: 100
  future_steps: 1
dataloader_args:
  num_workers: 0
  batch_size: 100
  shuffle: True
train_epochs: 500
evaluation: None