device: cpu
model_name: ModelLSTM
model_args:
  log: True
  hidden_dim: 54
  xavier_init: True
  out_act: sigmoid
dataset_args:
  d_type: train
  normalize: True
  bounds: [0, 1]
  sequence_length: 200
dataloader_args:
  num_workers: 0
  batch_size: 10
  shuffle: true
train_epochs: 10
evaluation: None