device: cpu
model_name: ModelLSTM
model_args:
  log: True
  lr: 0.02
  lr_decay: 0.99
  adam_betas: [0.3, 0.5]
  hidden_dim: 128
  xavier_init: True
  out_act: sigmoid
dataset_args:
  d_type: train
  normalize: True
  bounds: [0, 1]
  sequence_length: 10
  future_steps: 1
dataloader_args:
  num_workers: 0
  batch_size: 100
  shuffle: True
train_epochs: 500
evaluation: None