seed_everything: true
trainer:
  callbacks: 
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: validate/MSELoss
        min_delta: 0.0001
        patience: 5
  precision: 32
  max_epochs: 15
  profiler: null #"simple"
model:
  class_path: TimeSeriesDL.model.Seq2Seq
  init_args:
    in_features: 5
    hidden_dim: 64
    gru_layers: 2
    dropout: 0.1
    probabilistic: true
    attention: true
    teacher_force: 0.2
    out_act: sigmoid
    loss: GaussianNLLLoss
    optimizer: Adam
    lr: 0.0001
data:
  files:
    - examples/data/train_1.csv
    - examples/data/train_2.csv
    - examples/data/train_3.csv
    - examples/data/train_4.csv
  data_kwargs:
    scaler: normalize
    sequence_length: 500
    future_steps: 50
  loader_kwargs:
    batch_size: 128
    shuffle: True
    num_workers: 3
    persistent_workers: True