dataset:
  d_type: train
  sequence_length: 32
  custom_path: ./examples/train.mat
dataloader:
  batch_size: 16
model_name: SimpleModel
model_path: None
model:
  input_size: 1
train_epochs: 5
device: cuda