dataset:
  sequence_length: 2500
  future_steps: 100
  path: 
    - ./examples/train_1.mat
    - ./examples/train_2.mat
    - ./examples/train_3.mat
  
testset:
  sequence_length: 2500
  future_steps: 100
  path: ./examples/train_4.mat
  
dataloader:
  batch_size: 64
  shuffle: True

trainer:
  epochs: 10
  save_every: 2

loss_suite:
  main: MSELoss
  log:
    - L1Loss
  optimizer: Adam
  lr: 0.001
  lr_decay: 0.999

model_name: ConvLSTM
model_path: None
model:
  sequence_length: 2500
  future_steps: 100
  features: 5
  latent_size: 16
  kernel_size: 25
  stride: 10
  padding: 0
  lstm_layers: 2
  hidden_dim: 128

precision: float32
device: mps