dataset:
  d_type: train
  sequence_length: 2500
  future_steps: 100
  custom_path: ./examples/train_3.mat
  ae_mode: True
  
testset:
  d_type: test
  sequence_length: 2500
  future_steps: 100
  custom_path: ./examples/train_4.mat
  ae_mode: True
  
dataloader:
  batch_size: 64
  shuffle: True

trainer:
  epochs: 10
  save_every: 5

loss_suite:
  main: MSELoss
  log:
    - BCELoss
    - L1Loss
  optimizer: Adam
  lr: 0.001
  lr_decay: 0.999

model_name: ConvAE
model_path: None
model:
  features: 5
  sequence_length: 2500
  channels: 1
  extracted_features: 8
  latent_size: 16
  kernel_size: 10
  stride: 1
  padding: 0
  tag: AE-LSTM

precision: float32
device: mps