name: Python Package using Conda

on: [push]

jobs:
  test-package:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        channels: pytorch, conda-forge, defaults
        auto-activate-base: false
        activate-environment: test
        environment-file: environment-cpu.yml

    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Build Package
      run: |
        pip install .

    - name: Run Unittests
      run: |
        python -m unittest discover -s tests -v
